version: '3'
services:
  client:
    image: 'rallycoding/multi-client'
    hostname: client
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 100M
  server:
    image: 'rallycoding/multi-server'
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 100M
  worker:
    image: 'rallycoding/multi-worker'
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 100M
  nginx:
    image: 'rallycoding/multi-nginx'
    hostname: nginx
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 100M
